# ===============================
#   CONFIGURACIÓN DE LA APLICACIÓN
# ===============================
spring.application.name=MensajeriaBethel

# ===============================
#   CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL Render) - Conexión Externa
# ===============================
# URL, usuario y contraseña corregidos
spring.datasource.url=jdbc:postgresql://dpg-d3ntbkodl3ps739btd9g-a.oregon-postgres.render.com/mensajeriabethel
spring.datasource.username=samper
spring.datasource.password=kfDm8VKl8BFsq4qgngeKYShJMpqZnm4V

# === PROPIEDADES PARA FORZAR SSL EN RENDER ===
spring.datasource.properties.sslmode=require
spring.datasource.properties.sslfactory=org.postgresql.ssl.NonValidatingFactory
# =============================================

# ===============================
#   CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
#   CONFIGURACIÓN SMTP CORREGIDA
# Usando Puerto 465 (SSL) y la Contraseña de Aplicación.
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=buzonfisitecnolcolegiobethel@gmail.com
# Contraseña de Aplicación de 16 caracteres de Google (sin espacios)
spring.mail.password=ytmjkhfyuwbqekzs
spring.mail.properties.mail.smtp.auth=true
# Habilitamos SSL (requerido para el puerto 465)
spring.mail.properties.mail.smtp.ssl.enable=true
# Deshabilitamos STARTTLS (ya que estamos usando SSL puro en 465)
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000